### ISSUE TITLE
BUG Report

### ISSUE THREAD

**Issue by unauth401** [lifegpc/bili#107]
近期（一周内）不知道为什么一旦连着下载超过五个视频就会报`获取文件大小失败。尝试重新获取……`
滚动速度极快
此时ctrl+c有时候是keyboard interrupt有时候是local issuer failed to verify（原文复现不出来，大概意思是证书验证错误）

日志已发到邮箱 请查收

**Comment by JureGrinffin** [comment]
PS: 也不一定是五个
只要请求比较快就会炸
一两个还是没什么问题的

**Comment by JureGrinffin** [comment]
似乎B站视频API更新了
现在已经无法下载视频

**Comment by lifegpc** [comment]
试试dev分支，普通视频的视频下载解析应该OK了

**Comment by JureGrinffin** [comment]
现在能用了
谢

**Comment by bottomash** [comment]
> 试试dev分支，普通视频的视频下载解析应该OK了

怎么使用dev分支？我下载dev分支的代码然后解压缩。
用py start.py命令，然后报错。
Traceback (most recent call last):
  File "D:\bilidev\start.py", line 28, in <module>
    import PrintInfo
  File "D:\bilidev\PrintInfo.py", line 16, in <module>
    from command import gopt
  File "D:\bilidev\command.py", line 19, in <module>
    from file import filterd
  File "D:\bilidev\file\__init__.py", line 19, in <module>
    from lang import getdict, getlan
  File "D:\bilidev\lang.py", line 16, in <module>
    import polib
ModuleNotFoundError: No module named 'polib'

正确使用dev分支的方式是？感谢大佬的付出，

**Comment by lifegpc** [comment]
> > 试试dev分支，普通视频的视频下载解析应该OK了
> 
> 怎么使用dev分支？我下载dev分支的代码然后解压缩。 用py start.py命令，然后报错。 Traceback (most recent call last): File "D:\bilidev\start.py", line 28, in import PrintInfo File "D:\bilidev\PrintInfo.py", line 16, in from command import gopt File "D:\bilidev\command.py", line 19, in from file import filterd File "D:\bilidev\file__init__.py", line 19, in from lang import getdict, getlan File "D:\bilidev\lang.py", line 16, in import polib ModuleNotFoundError: No module named 'polib'
> 
> 正确使用dev分支的方式是？感谢大佬的付出，

`python -m pip install -r requirements.txt`

**Comment by bottomash** [comment]
使用后确实能用了，但是这样下载的代码里没有 aria2c.exe和ffmpeg.exe文件。手动复制这两个exe文件后aria2c功能正常使用，但是视频和音频下载完不会合并，应该是ffmpeg合拼视频这一步出差错了。这个问题应该怎么解决？谢谢大佬。

**Comment by lifegpc** [comment]
可以把ffmpeg.exe放到`C:/Windows/` 那个文件夹里的exe一般都能被找到

**Comment by bottomash** [comment]
把ffmpeg.exe 放到了c:/windows那个文件夹了（我也关机重启了）。其实我用scoop装了ffmpeg，也添加到了环境变量里。
如图：
![image](https://user-images.githubusercontent.com/48351249/142603742-fc03cd01-8d0c-4253-a6af-1381677f3b3f.png)

但是就是没法用ffmpeg合并？

大佬考虑更新一个小版本修复普通视频解析吗？感谢大佬回复。
