### ISSUE TITLE
BUG Report

### ISSUE THREAD

**Issue by YuanHao0** [lifegpc/bili#108]
今天开始突然不能下载视频：
打开主程序可以正常运行且成功登录，但是在询问选择下载选项时选择了3-下载视频后，程序自动闪退。请查看日志文件
[AV420682551_1635368241.log](https://github.com/lifegpc/bili/files/7429250/AV420682551_1635368241.log)

**Comment by AOKIKAORU** [comment]
遇到了相同的问题。程序结束前给出如下信息

Traceback (most recent call last):
    File "start.py", line 2700, in <module>
    File "start.py", line 2412, in main
    File "videodownload.py", lin 1667, in avvideodownload
UnboundLocalError: local variable 'filen' referenced before assignment
[15364] Failed to execute script start

**Comment by EVANGELION-Air** [comment]
> 相同的问题，输入下载选项为3后就自动结束 启动时添加-d3也是如此 目前无法下载视频

更新，该问题已不存在，应当是b站自身问题
