### ISSUE TITLE
希望可以加一个全局配置 能够做到全自动

### ISSUE THREAD

**Issue by maxiang19920422** [lifegpc/bili#47]
您好,如题 
       就是在进行大批量下载时, 每一个下载前都需要选择 <<请输入你要下载的方式>>(我都是选 3.视频下载 )  以及多P时 输入下载的范围(我都是填 a) 因为我每次选的都是一样的  
       **希望可以加一个全局的设置 在任务开始前 能够选择 1. 每次下载一个新的资源都进行设置这两个参数  2. 一次设置所有的两个参数** 
       这样夜里就可以进行全自动下载 不需要每次都进行选择了 
PS:  我刚用几天 也可能是已经有这个功能了 我还没有发现 如果有的话 希望能说明一下谢谢

**Comment by lifegpc** [comment]
您可以使用命令行，命令行怎么使用可以谷歌。
命令行示例：```py start.py -d3 -pa```

**Comment by lifegpc** [comment]
命令行所有帮助可以通过 ```py start.py -h```查看

**Comment by maxiang19920422** [comment]
十分感谢!!!

**Comment by maxiang19920422** [comment]
您好 我又来了  下载的很稳定 十分感谢~  但是有个小问题 就是 那些地址需要自己一个一个复制... 有没有可以获取一个UP主的所有视频地址的功能呢

**Comment by lifegpc** [comment]
是有这个功能的，UP主个人空间（PC端）切换至投稿、频道、收藏页均可以使用批量下载

**Comment by lifegpc** [comment]
例如输入 ```https://space.bilibili.com/9617619/video``` 程序会自动抓取这个UP主的所有投稿视频，然后让你选择要下载的视频。

**Comment by maxiang19920422** [comment]
哇  功能真的强大  我再研究研究 十分感谢~~

**Comment by maxiang19920422** [comment]
您好 我又来了 (●ˇ∀ˇ●)   这两天 B站可能进行了更新  下载的多了 会出现一个验证 然后任务就终止了 报错信息如下:

> DevTools listening on ws://127.0.0.1:13272/devtools/browser/831ec061-06ca-4b85-aba2-cfedfa32d603
Traceback (most recent call last):
  File "biliLogin.py", line 181, in dealwithcap
  File "selenium\webdriver\chrome\webdriver.py", line 81, in __init__
  File "selenium\webdriver\remote\webdriver.py", line 157, in __init__
  File "selenium\webdriver\remote\webdriver.py", line 252, in start_session
  File "selenium\webdriver\remote\webdriver.py", line 321, in execute
  File "selenium\webdriver\remote\errorhandler.py", line 242, in check_response
selenium.common.exceptions.SessionNotCreatedException: Message: session not created: This version of ChromeDriver only supports Chrome version 87
Current browser version is 86.0.4240.198 with binary path C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

> DevTools listening on ws://127.0.0.1:13289/devtools/browser/6b9a9ce6-2d49-452a-b79c-510aefa9f7e4
Traceback (most recent call last):
  File "biliLogin.py", line 181, in dealwithcap
  File "selenium\webdriver\chrome\webdriver.py", line 81, in __init__
  File "selenium\webdriver\remote\webdriver.py", line 157, in __init__
  File "selenium\webdriver\remote\webdriver.py", line 252, in start_session
  File "selenium\webdriver\remote\webdriver.py", line 321, in execute
  File "selenium\webdriver\remote\errorhandler.py", line 242, in check_response
selenium.common.exceptions.SessionNotCreatedException: Message: session not created: This version of ChromeDriver only supports Chrome version 87
Current browser version is 86.0.4240.198 with binary path C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

> DevTools listening on ws://127.0.0.1:13306/devtools/browser/0cc18493-20a4-47b2-ad73-7df32bff9434
Traceback (most recent call last):
  File "biliLogin.py", line 181, in dealwithcap
  File "selenium\webdriver\chrome\webdriver.py", line 81, in __init__
  File "selenium\webdriver\remote\webdriver.py", line 157, in __init__
  File "selenium\webdriver\remote\webdriver.py", line 252, in start_session
  File "selenium\webdriver\remote\webdriver.py", line 321, in execute
  File "selenium\webdriver\remote\errorhandler.py", line 242, in check_response
selenium.common.exceptions.SessionNotCreatedException: Message: session not created: This version of ChromeDriver only supports Chrome version 87
Current browser version is 86.0.4240.198 with binary path C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

> 请在浏览器中打开"https://www.bilibili.com/video/avxxxxxxxxx"并且通过验证。

**Comment by lifegpc** [comment]
你下载太多被B站风控了，打开浏览器（相同IP、相同账号）应该能看到错误信息，然后你需要通过验证（如果有验证码），如果没验证码请耐心等待B站解封（大概几个小时）。

**Comment by lifegpc** [comment]
如果你可以更新你的Chrome至最新版本，你应该直接就能看到那个需要验证的界面。

**Comment by maxiang19920422** [comment]
好的  谢谢啦  那我下载UP的所有视频的时候 可以指定从第几页到第几页吗 
因为失败了之后 再重新下载的话 输入UP的主页 又会从第一页开始查询了

**Comment by lifegpc** [comment]
暂时还不可以，但你可以选择从第几个视频到第几个视频
1-50,60-70,72
以上会选择第1个到第50个视频，第60到第70个视频，还有第72个视频

**Comment by maxiang19920422** [comment]
好的 谢谢啦 我先升级chrome看看
