### ISSUE TITLE
BUG Report: 下载出错

### ISSUE THREAD

**Issue by ASC8384** [lifegpc/bili#61]
下载`BV1S4411x7Te`时，网页提示`视频撞车`，调试时发现
```
"error":{"code":404,"trueCode":-200,"forward":"\u002Fvideo\u002Fav39232896"}
```
最后输出
```
Traceback (most recent call last):                         
  File "start.py", line 2321, in <module>                  
    main(ip)                                               
  File "start.py", line 1830, in main                      
    data=JSONParser.Myparser(parser.videodata)             
  File "D:\Code\bili\JSONParser.py", line 34, in Myparser  
    data['bvid']=obj['videoData']['bvid']                  
KeyError: 'bvid'                                           
```

**Comment by lifegpc** [comment]
复现了（
