### ISSUE TITLE
[1784] Failed to execute script start

### ISSUE THREAD

**Issue by yinzhefuyun** [lifegpc/bili#9]
bili  版权所有 (C) 2019-2020  lifegpc
    This program comes with ABSOLUTELY NO WARRANTY; for details type `show w'.
    本程序不负任何担保责任，欲知详情请键入'show w'。
    This is free software, and you are welcome to redistribute it
    under certain conditions; type `show c' for details.
    这是一个自由软件，欢迎您在特定条件下再发布本程序；欲知详情请键入'show c'。
    You can find the source code on <https://github.com/lifegpc/bili>.
    你可以在<https://github.com/lifegpc/bili>上找到源代码。

建议运行setsettings.py设置程序以减少不必要的询问。
请输入av号（支持SS、EP号，BV号请以BV开头，现在已支持链接，支持用户页的收藏夹、频道、投稿链接）：BV1fK4y1t7hj

DevTools listening on ws://127.0.0.1:2509/devtools/browser/9e799119-3ffa-4455-86c9-67819adcb960
Traceback (most recent call last):
  File "start.py", line 948, in <module>
  File "start.py", line 200, in main
  File "biliLogin.py", line 22, in login
  File "site-packages\selenium\webdriver\chrome\webdriver.py", line 81, in __init__
  File "site-packages\selenium\webdriver\remote\webdriver.py", line 157, in __init__
  File "site-packages\selenium\webdriver\remote\webdriver.py", line 252, in start_session
  File "site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
  File "site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
selenium.common.exceptions.SessionNotCreatedException: Message: session not created: This version of ChromeDriver only supports Chrome version 80

[1784] Failed to execute script start

**Comment by yinzhefuyun** [comment]
因为只用是chrome83，bili自带的是80版本，下载对应版本就好了https://chromedriver.chromium.org/downloads

**Comment by lifegpc** [comment]
有时候最新版本也会出问题，需要旧一点的版本（我出过问题
